function on(evName, action) {
    return function(el) {
        return el.addEventListener(evName, action);
    };
}
on.click = function(action) { return on('click', action) };
on.contextmenu = function(action) { return on('contextmenu', action) };
on.dblclick = function(action) { return on('dblclick', action) };
on.mousedown = function(action) { return on('mousedown', action) };
on.mouseenter = function(action) { return on('mouseenter', action) };
on.mouseleave = function(action) { return on('mouseleave', action) };
on.mousemove = function(action) { return on('mousemove', action) };
on.mouseover = function(action) { return on('mouseover', action) };
on.mouseout = function(action) { return on('mouseout', action) };
on.mouseup = function(action) { return on('mouseup', action) };
on.abort = function(action) { return on('abort', action) };
on.load = function(action) { return on('load', action) };
on.scroll = function(action) { return on('scroll', action) };
on.blur = function(action) { return on('blur', action) };
on.change = function(action) { return on('change', action) };
on.focus = function(action) { return on('focus', action) };
on.focusin = function(action) { return on('focusin', action) };
on.focusout = function(action) { return on('focusout', action) };
on.input = function(action) { return on('input', action) };
on.invalid = function(action) { return on('invalid', action) };
on.reset = function(action) { return on('reset', action) };
on.search = function(action) { return on('search', action) };
on.select = function(action) { return on('select', action) };
on.submit = function(action) { return on('submit', action) };
on.drag = function(action) { return on('drag', action) };
on.dragend = function(action) { return on('dragend', action) };
on.dragenter = function(action) { return on('dragenter', action) };
on.dragleave = function(action) { return on('dragleave', action) };
on.dragover = function(action) { return on('dragover', action) };
on.dragstart = function(action) { return on('dragstart', action) };
on.drop = function(action) { return on('drop', action) };
on.copy = function(action) { return on('copy', action) };
on.cut = function(action) { return on('cut', action) };
on.paste = function(action) { return on('paste', action) };
on.animationend = function(action) { return on('animationend', action) };
on.animationiteration = function(action) { return on('animationiteration', action) };
on.animationstart = function(action) { return on('animationstart', action) };
on.transitionend = function(action) { return on('transitionend', action) };
on.show = function(action) { return on('show', action) };
on.toggle = function(action) { return on('toggle', action) };
on.wheel = function(action) { return on('wheel', action) };